name: Test Runner

on:
  workflow_dispatch:   # manual trigger

jobs:
  test:
    runs-on: self-hosted   # yeh Saturn/Windows runner pick karega
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello from $(uname -a) running on GitHub Self-hosted Runner 🎉"
